### ISSUE TITLE
using spreadsheet web components with react 

### ISSUE THREAD

**Issue by faycelbouamoud** [vaadin/spreadsheet#697]
Hello,
I tried to play a little with vaadin spreadsheet web components with react and discover it but I didn't find it in npm.
Thanks

**Comment by alvarezguille** [comment]
Spreadsheet is an add-on Component for Vaadin Framework 7 and 8, there is no web component version at the moment. I'll close this issue.
Looks like information in https://vaadin.com/components/vaadin-spreadsheet for this components is not 100% accurate at the moment and it will be fixed in the website.
